# Generated by Django 3.1.3 on 2020-12-06 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Business',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
