# Generated by Django 3.1.3 on 2020-11-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=16)),
                ('LoginStatus', models.BooleanField(default=False)),
                ('RegisterDate', models.CharField(max_length=23)),
                ('Email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Custmer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('Name', models.CharField(max_length=100)),
                ('addres', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Age', models.IntegerField(max_length=3)),
            ],
            bases=('accounts.user',),
        ),
    ]
