# Generated by Django 3.1.3 on 2020-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
