# Generated by Django 3.1.3 on 2020-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=16)),
                ('Email', models.CharField(max_length=40)),
                ('NameBusiness', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('addres', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='LoginStatus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='RegisterDate',
        ),
        migrations.DeleteModel(
            name='Custmer',
        ),
    ]
