# Generated by Django 3.1.3 on 2020-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_comments',
            field=models.CharField(default='no additional comments', max_length=255),
        ),
    ]
