# Generated by Django 3.1.3 on 2020-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20201130_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(max_length=200),
        ),
    ]
