# Generated by Django 3.1.3 on 2020-12-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_info', models.TextField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_amount', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='static/images/products_Pictures')),
            ],
        ),
    ]
