# Generated by Django 3.1.3 on 2020-12-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201206_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=0, upload_to='static/images/products_Pictures'),
            preserve_default=False,
        ),
    ]
